### ISSUE TITLE
[questions/qa-upright-counters-in-vertical]  Large number of items and CJK punctuation characters

### ISSUE THREAD

**Issue by yamahige** [w3c/i18n-drafts#626]
[source] (https://w3c.github.io/i18n-drafts/questions/qa-upright-counters-in-vertical.html) [en]

How about including these features to inspire more comments.
- items with larger digits
- including CJK punctuation characters to clarify spacing control, as @taroyamamoto-451 [commented in "4."](https://github.com/w3c/i18n-drafts/issues/620#issue-2693367921)
  * at the start of the prefix and the end of the suffix of "::marker"
  * at the start and the end of the item's body

For example:

CSS
```css
:root {
    writing-mode: vertical-rl;
    text-spacing-trim: trim-start;
}
```

HTML
```html
<ol>
    <li>仕込む前に生芋を１／４ぐらいの大きさにカット。</li>
    <li>すり潰した生芋</li>
    <li>ながらのパケット式の定量練り、通称バタ練り機</li>
    <li>…</li>
    <li value="9">「仕込む前に生芋を１／４ぐらいの大きさにカット。」</li>
    <li>（すり潰した生芋）</li>
    <li>ながらのパケット式の定量練り、<br>「通称バタ練り機」<br>ああああ</li>
    <li>…</li>
    <li value="99">仕込む前に生芋を１／４ぐらいの大きさにカット。</li>
    <li>すり潰した生芋</li>
    <li>ながらのパケット式の定量練り、<br>（通称バタ練り機）<br>ああああ</li>
</ol>
```

Or:

CSS
```css
:root {
    writing-mode: vertical-rl;
    text-spacing-trim: trim-start;
}
ol.my {
    counter-reset: my-counter 0;
    padding-inline-start: 2em;
    & li {
        list-style: none;
        counter-increment: my-counter;
        .marker {
            margin-inline-start: -2em;
        }
        .marker::before {
            content: "（";
        }
        .marker::after {
            content: "）";
        }
        .marker .body::before {
            content: counter(my-counter);
            text-combine-upright: all;
        }
    }
}
```
 HTML
```html
<ol class="my">
    <li><span class="marker"><span class="body"></span></span>仕込む前に生芋を１／４ぐらいの大きさにカット。</li>
    <li><span class="marker"><span class="body"></span></span>すり潰した生芋</li>
    <li><span class="marker"><span class="body"></span></span>ながらのパケット式の定量練り、通称バタ練り機</li>
    <li><span class="marker"><span class="body"></span></span>…</li>
    <li style="counter-set: my-counter 9;"><span class="marker"><span class="body"></span></span>「仕込む前に生芋を１／４ぐらいの大きさにカット。」</li>
    <li><span class="marker"><span class="body"></span></span>（すり潰した生芋）</li>
    <li><span class="marker"><span class="body"></span></span>ながらのパケット式の定量練り、<br>「通称バタ練り機」<br>ああああ</li>
    <li><span class="marker"><span class="body"></span></span>…</li>
    <li style="counter-set: my-counter 99;"><span class="marker"><span class="body"></span></span>仕込む前に生芋を１／４ぐらいの大きさにカット。</li>
    <li><span class="marker"><span class="body"></span></span>すり潰した生芋</li>
    <li><span class="marker"><span class="body"></span></span>ながらのパケット式の定量練り、<br>（通称バタ練り機）<br>ああああ</li>
</ol>
```

**Comment by r12a** [comment]
This is clever.  It's a bit far from the standard way of creating lists, though — this can be problematic, for example, if you want to apply this style to existing content without changing the HTML.  So i'm holding out for support of `text-combine-upright:digits` for a solution here.

**Comment by r12a** [comment]
Fwiw, here's an image of the output:

<p  dir=rtl>
<img width="296" alt="Image" src="https://github.com/user-attachments/assets/3410645a-6638-4e62-8d64-48cfc4cae5c6" />
</p>

**Comment by yamahige** [comment]
> So i'm holding out for support of `text-combine-upright:digits` for a solution here.

Me too. The mixing style is popular in vertically-set Japanese scholarly articles.

**Comment by yamahige** [comment]
> Nested pseudo elements styling - Chrome 135
https://developer.chrome.com/release-notes/135#nested_pseudo_elements_styling

Wow!
Though it is still tricky and has problems with indentation, this new feature allows the style to be applied to existing content without changing the HTML.

CodePen https://codepen.io/yamahige/pen/yyLwYpe

![Image](https://github.com/user-attachments/assets/c08ac279-3fc9-4d72-962a-17219e7354bc)

```css
:root {
    writing-mode: vertical-rl;
}
ol {
    padding-inline-start: .5em;
}
ol li {
    display: list-item;
    list-style-type: none;
}
ol li::marker {
    content: "(";
}
ol li::before {
    display: list-item inline;
    content: ")";
    margin-inline-end: .5em;
}
ol li::before::before {
    /*
    This does not work...
    */
    content: "(";
}
ol li::before::marker {
    text-combine-upright: all;
    content: counter(list-item);
}
```

```html
<ol>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>…</li>
    <li style="counter-set: list-item 9;">色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>…</li>
    <li style="counter-set: list-item 99;">色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
    <li>色は匂へど散りぬるを我が世誰ぞ常ならむ有為の奥山今日越えて浅き夢見し酔ひもせず。</li>
</ol>
```
